version: '3.8'

services:
  nginx:
    container_name: simple-article-nginx # 아래의 이미지로 띄울 컨테이너의 이름 지정
    image: nginx:latest # 가지고있는 이미지 명
    volumes:
      - ./out/artifacts/nft_admin_main_jar:/share
    ports:
      - 80:80

  mariadb:
    container_name: simple-article-mariadb
    image: mariadb:10.8.3
    volumes:
      - ./share:/share
      - ./init/:/docker-entrypoint-initdb.d/ #sql 스크립트 파일은 반드시 docker-entrypoint-initdb.d 안으로 넣어야한다.
    ports:
      - 4445:3306
    environment: # 환경 변수 전달
      MYSQL_ROOT_PASSWORD: "0000" # root 패스워드 지정
      MYSQL_DATABASE: "simple_article_db" # 초기 디비 생성
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

