spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://10.0.0.138:4444/nft_demo
    username: root
    password: '0000'

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
Loggin:
  level:
    org.hibernate.SQL: debug