spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/simplearticleapih2
    username: sa
    password :
    deriver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
  #2.5이상의 버전부터 data.sql 스크립트는 Hibernate가 초기화되기 전에 실행된다고 한다.
  #data.sql을 사용하여 Hibernate에 의해 생성된 스키마를 채우려면
  #spring.jpa.defer-datasource-initialization을 true로 설정하라고 지시되어 있다.

  sql:
    init:
      mode: always #ALWAYS: 모든 데이터베이스에 sql 스크립트를 동작시킨다.
Loggin:
  level:
    org.hibernate.SQL: debug