INSERT INTO MEMBER (LOGIN_ID, LOGIN_PWD, NICK_NAME)  VALUES ('admin1', '$2a$10$1PdZ.5oP5vj2oSJNaBWlGO3XAo38.sXfgup/LVpasxzzNmBrd8dly', 'admin1NickName');
INSERT INTO MEMBER (LOGIN_ID, LOGIN_PWD, NICK_NAME)  VALUES ('user1', '$2a$10$x5ItQ0I/FMmWxBE5tLDh3ex.0w.O.YjfDvMS/T349nl.Hqhy84gL', 'user1NickName');
--
INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_USER');
INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_ADMIN');
--
INSERT INTO USER_AUTHORITY (LOGIN_ID, AUTHORITY_NAME) values ('admin1', 'ROLE_ADMIN');
INSERT INTO USER_AUTHORITY (LOGIN_ID, AUTHORITY_NAME) values ('user1', 'ROLE_USER');